### ISSUE TITLE
questions & suggestions

### ISSUE THREAD

**Issue by ghost** [binkybear/HoneyPi#1]
hi,

1st the questions : 
*Have you tried testing this script?
*On which devices have you tested it?
*What devices would you suggest to use for testing?
*Wouldn't be usefull to use "screen" for running all the tools all together?
*What about GUI option for?
2nd the suggestions:
 *If you wanna have to use menu and such : check out dialog/whiptail? (ncurses based)
 *You could install all the packages as prerequisite to run the script(kind of dependency) thus avoid problems later on.
  *also check out the some alike projects e.g. fruttywifi, mana-toolkit, Pineapple pi and so on.
thanks inadvance

**Comment by binkybear** [comment]
Hi @silent-mobius!  Let me try to answer all the questions:
- I have not tested the script but I did test the commands to install each program, so this was originally more of a "reference" script.  I had planned on making it into a complete installer on my raspberry pi but I got busy with other projects.
- Each install was tested on a clean raspbian on the 1st gen Pi.  Everything seemed to run smoothly.
  It's possible to use screen to run everything but most of these programs will run in the background fine.
- I had actually planned on released a Pi img that could easily be flashed to a sdcard to save time and make it easier to get a honeypot running but like I mentioned, time got to me.

I do like your suggestions.  I am very familiar with fruitywifi and mana-toolkit.  I think having a web based installer would be nice and there's been a lot of honeypot projects that I could see adding to the script.

Like I mentioned, the intention was to make it deploy a honeypot quickly on a raspberry PI and I think if I had to do it again I would go in a different direction. 

Something similar to the Modern Honey Network:
https://zeltser.com/modern-honey-network-experiments/

**Comment by ghost** [comment]
Hi binkyBear,
I have edit your script: devided, reshaped and working towards making it a service/daemon to work on any linux/unix machine, big or small.( i have this fetish of running everything from background and monitor for results) maybe even make debian package out of it.
what i was trying to say with all this is, that i'll be happy to help in scripting, planning, design & so on.

**Comment by binkybear** [comment]
@silent-mobius - Thanks for the feedback and feel free to change/modify the script.  I can add you as a contributor as i'm not maintaining it at the moment.

**Comment by ghost** [comment]
@binkybear -Thanks, i'll be glad to.
